### PR TITLE
WIP, Update to JuMP v0.19

### PR DESCRIPTION
**Pull request by ccoffrin**
@odow, got any time to do classes 2 and 5?

### CODE REVIEW

**Comment by ccoffrin** [comment]
@odow, bump. 😃

**Comment by odow** [comment]
I might have some time this week. Otherwise I'm going to be spending a lot of time sitting in airports next week, so I can do it then.

**Comment by ccoffrin** [comment]
Great.  No rush, plan to do in airport downtime. ✈️

**Comment by odow** [comment]
@ccoffrin here you go.

**Comment by ccoffrin** [comment]
Thank you sir!

**Pull request merged**
